site_name: AmeisenBot Docs
docs_dir: docs
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - c#
        - nasm
nav:
- 'index.md'
- 'AmeisenBot.Core.md':
  - 'ameisencore/AmeisenCore.md'
  - 'ameisencore/AmeisenHook.md'
  - 'ameisencore/AmeisenEventHook.md'